name: Run tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Run server tests
        run: npm test
        working-directory: ./server
        env:
          SECRET: ${{ secrets.SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ISSUER: ${{ secrets.ISSUER }}

      - name: Install client dependencies
        run: npm ci
        working-directory: ./client

      - name: Run client tests
        run: npm test
        working-directory: ./client