name: Run tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Create Firebase service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebaseServiceAccountKey.json
        working-directory: ./server

      - name: Run server tests
        run: npm test
        working-directory: ./server
        env:
          SECRET: ${{ secrets.SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ISSUER: ${{ secrets.ISSUER }}

      - name: Install client dependencies
        run: npm install
        working-directory: ./client
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

      - name: Run client tests
        run: npm test
        working-directory: ./client

